#!/bin/bash

set -e

v="1.0.0.0 RC"

function usage {
	cat << USAGE

Auto IPA Builder v$v

Usage: build 'option'

Help: 
      build 'ipalist' - Shows the list of required IPAs and their names
      build 'optionslist' - Shows the list of options for the build command

USAGE
	exit 1
}

[[ $# = 0 ]] && usage

commands=(ipalist optionslist audiomackpp cercube twitchpp)
[[ ! " ${commands[@]} " =~ " $1 " ]] && usage

function ipalist {
	echo "IPAs must be in a folder called Ipas on your Desktop"
	echo "IPAs:
      Audiomack.ipa
      Twitch.ipa
      YouTube.ipa"
}

function optionslist {
	echo "Options:
      audiomackpp - Builds Audiomack++
      cercube - Builds Cercube for YouTube
      twitchpp - Builds Twitch++"
}

function audiomackpp {
	echo "Building Audiomack++"
	cd ~/Desktop/Ipas
	mkdir -p Build
	cd Build
	rm -r -f Audiomack > /dev/null
	echo "Extracting IPA"
	unzip ../Audiomack.ipa -d Audiomack > /dev/null
	cd "Audiomack";
	echo "Downloading Tweak"
	curl -O "https://raw.githubusercontent.com/SarahH12099/SarahH12099.github.io/master/repo/debs/Audiomack.deb"
	echo "Downloading Tweak Dependencies"
	curl -O "https://raw.githubusercontent.com/SarahH12099/Auto-IPA-Builder/master/Files/CydiaSubstrateFramework.zip"
	curl -O "https://raw.githubusercontent.com/SarahH12099/Auto-IPA-Builder/master/Files/libloader.zip"
	echo "Extracting Tweak And Tweak Dependencies"
	dpkg-deb -R "Audiomack.deb" Tweak > /dev/null
	unzip CydiaSubstrateFramework.zip -d CydiaSubstrateFramework > /dev/null
	unzip libloader.zip -d libloader > /dev/null
	echo "Converting Tweak To Non-Jailbreak"
	cd Tweak/Library/MobileSubstrate/DynamicLibraries
	install_name_tool -change /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate @rpath/CydiaSubstrate.framework/CydiaSubstrate "AudiomackCrack.dylib" > /dev/null
	echo "Moving Tweak And Tweak Dependencies"
	cd ../../../../
	mkdir -p Payload/audiomack-iphone.app/libloader > /dev/null
	cp Tweak/Library/MobileSubstrate/DynamicLibraries/AudiomackCrack.dylib Payload/audiomack-iphone.app/libloader > /dev/null
	cp libloader/Sys.dylib Payload/audiomack-iphone.app > /dev/null
	cp -R CydiaSubstrateFramework/Frameworks Payload/audiomack-iphone.app > /dev/null
	echo "Injecting Tweak"
	cd Payload/audiomack-iphone.app
	install_name_tool -change /usr/lib/libSystem.B.dylib @executable_path/Sys.dylib "audiomack-iphone" > /dev/null
	cd ../../
	echo "Cleaning Left Over Files"
	rm -r -f Audiomack.deb > /dev/null
	rm -r -f CydiaSubstrateFramework.zip > /dev/null
	rm -r -f libloader.zip > /dev/null
	rm -r -f Tweak > /dev/null
	rm -r -f CydiaSubstrateFramework > /dev/null
	rm -r -f libloader > /dev/null
	echo "Packaging IPA"
	zip -r -X ../"Audiomack++.ipa" * > /dev/null
	cd ../; rm -r -f Audiomack > /dev/null
	echo "Done Building Audiomack++"
}

function cercube {
	echo "Building Cercube for YouTube"
	cd ~/Desktop/Ipas
	mkdir -p Build
	cd Build
	rm -r -f YouTube > /dev/null
	echo "Extracting IPA"
	unzip ../YouTube.ipa -d YouTube > /dev/null
	cd "YouTube";
	echo "Downloading Tweak"
	curl -O "https://raw.githubusercontent.com/SarahH12099/Auto-IPA-Builder/master/Tweaks/Cercube.zip"
	echo "Downloading Tweak Dependencies"
	curl -O "https://raw.githubusercontent.com/SarahH12099/Auto-IPA-Builder/master/Files/libloader.zip"
	echo "Extracting Tweak And Tweak Dependencies"
	unzip Cercube.zip -d Tweak > /dev/null
	unzip libloader.zip -d libloader > /dev/null
	echo "Moving Tweak And Tweak Dependencies"
	mkdir -p Payload/YouTube.app/libloader > /dev/null
	cp Tweak/Cercube.dylib Payload/YouTube.app/libloader > /dev/null
	cp libloader/Sys.dylib Payload/YouTube.app > /dev/null
	cp -R Tweak/Carida.bundle Payload/YouTube.app > /dev/null
	echo "Injecting Tweak"
	cd Payload/YouTube.app
	install_name_tool -change /usr/lib/libSystem.B.dylib @executable_path/Sys.dylib "YouTube" > /dev/null
	cd ../../
	echo "Cleaning Left Over Files"
	rm -r -f Cercube.zip > /dev/null
	rm -r -f libloader.zip > /dev/null
	rm -r -f Tweak > /dev/null
	rm -r -f libloader > /dev/null
	echo "Packaging IPA"
	zip -r -X ../"Cercube for YouTube.ipa" * > /dev/null
	cd ../; rm -r -f YouTube > /dev/null
	echo "Building Cercube for YouTube"
}

function twitchpp {
	echo "Building Twitch++"
	cd ~/Desktop/Ipas
	mkdir -p Build
	cd Build
	rm -r -f Twitch > /dev/null
	echo "Extracting IPA"
	unzip ../Twitch.ipa -d Twitch > /dev/null
	cd "Twitch";
	echo "Downloading Tweak"
	curl -O "https://raw.githubusercontent.com/SarahH12099/SarahH12099.github.io/master/repo/debs/Twitch.deb"
	echo "Downloading Tweak Dependencies"
	curl -O "https://raw.githubusercontent.com/SarahH12099/Auto-IPA-Builder/master/Files/CydiaSubstrateFramework.zip"
	curl -O "https://raw.githubusercontent.com/SarahH12099/Auto-IPA-Builder/master/Files/libloader.zip"
	echo "Extracting Tweak And Tweak Dependencies"
	dpkg-deb -R "Twitch.deb" Tweak > /dev/null
	unzip CydiaSubstrateFramework.zip -d CydiaSubstrateFramework > /dev/null
	unzip libloader.zip -d libloader > /dev/null
	echo "Converting Tweak To Non-Jailbreak"
	cd Tweak/Library/MobileSubstrate/DynamicLibraries
	install_name_tool -change /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate @rpath/CydiaSubstrate.framework/CydiaSubstrate "TwitchCrack.dylib" > /dev/null
	echo "Moving Tweak And Tweak Dependencies"
	cd ../../../../
	mkdir -p Payload/Twitch.app/libloader > /dev/null
	cp Tweak/Library/MobileSubstrate/DynamicLibraries/TwitchCrack.dylib Payload/Twitch.app/libloader > /dev/null
	cp libloader/Sys.dylib Payload/Twitch.app > /dev/null
	cp -R CydiaSubstrateFramework/Frameworks Payload/Twitch.app > /dev/null
	echo "Injecting Tweak"
	cd Payload/Twitch.app
	install_name_tool -change /usr/lib/libSystem.B.dylib @executable_path/Sys.dylib "Twitch" > /dev/null
	cd ../../
	echo "Cleaning Left Over Files"
	rm -r -f Twitch.deb > /dev/null
	rm -r -f CydiaSubstrateFramework.zip > /dev/null
	rm -r -f libloader.zip > /dev/null
	rm -r -f Tweak > /dev/null
	rm -r -f CydiaSubstrateFramework > /dev/null
	rm -r -f libloader > /dev/null
	echo "Packaging IPA"
	zip -r -X ../"Twitch++.ipa" * > /dev/null
	cd ../; rm -r -f Twitch > /dev/null
	echo "Done Building Twitch++"
}

"$1" "${@:2}"