#!/bin/bash

set -e

v="1.0.0.0 RC"

function usage {
	cat << USAGE

Auto IPA Builder v$v

Usage: build 'option'

Help: 
      build 'ipalist' - Shows the list of required IPAs and their names
      build 'optionslist' - Shows the list of options for the build command

USAGE
	exit 1
}

[[ $# = 0 ]] && usage

commands=(ipalist optionslist accuweatherpp audiomackpp cercube cercubepp twitchpp zinitevipp)
[[ ! " ${commands[@]} " =~ " $1 " ]] && usage

function ipalist {
	echo "IPAs must be in a folder called Ipas on your Desktop"
	echo "IPAs:
	  AccuWeather.ipa
      Audiomack.ipa
      Twitch.ipa
      YouTube.ipa
      ZiniTevi.ipa"
}

function optionslist {
	echo "Options:
	  accuweatherpp - Builds AccuWeather++
      audiomackpp - Builds Audiomack++
      cercube - Builds Cercube for YouTube
      cercubepp - Builds Cercube for YouTube++
      twitchpp - Builds Twitch++
      zinitevipp - Builds ZiniTevi++"
}

function accuweatherpp {
	echo "Building AccuWeather++"
	cd ~/Desktop/Ipas
	mkdir -p Build
	cd Build
	rm -r -f AccuWeather > /dev/null
	echo "Extracting IPA"
	unzip ../AccuWeather.ipa -d AccuWeather > /dev/null
	cd "AccuWeather";
	echo "Downloading Tweak"
	curl -O "https://raw.githubusercontent.com/SarahH12099/SarahH12099.github.io/master/repo/debs/AccuWeather.deb"
	echo "Downloading Tweak Dependencies"
	curl -O "https://raw.githubusercontent.com/SarahH12099/Auto-IPA-Builder/master/Files/CydiaSubstrateFramework.zip"
	curl -O "https://raw.githubusercontent.com/SarahH12099/Auto-IPA-Builder/master/Files/libloader.zip"
	echo "Extracting Tweak And Tweak Dependencies"
	dpkg-deb -R "AccuWeather.deb" Tweak > /dev/null
	unzip CydiaSubstrateFramework.zip -d CydiaSubstrateFramework > /dev/null
	unzip libloader.zip -d libloader > /dev/null
	echo "Converting Tweak To Non-Jailbreak"
	cd Tweak/Library/MobileSubstrate/DynamicLibraries
	install_name_tool -change /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate @rpath/CydiaSubstrate.framework/CydiaSubstrate "AccuWeatherCrack.dylib" > /dev/null
	echo "Moving Tweak And Tweak Dependencies"
	cd ../../../../
	mkdir -p Payload/AccuWeather.app/libloader > /dev/null
	cp Tweak/Library/MobileSubstrate/DynamicLibraries/AccuWeatherCrack.dylib Payload/AccuWeather.app/libloader > /dev/null
	cp libloader/Sys.dylib Payload/AccuWeather.app > /dev/null
	cp -R CydiaSubstrateFramework/Frameworks Payload/AccuWeather.app > /dev/null
	echo "Injecting Tweak"
	cd Payload/AccuWeather.app
	install_name_tool -change /usr/lib/libSystem.B.dylib @executable_path/Sys.dylib "AccuWeather" > /dev/null
	cd ../../
	echo "Cleaning Left Over Files"
	rm -r -f AccuWeather.deb > /dev/null
	rm -r -f CydiaSubstrateFramework.zip > /dev/null
	rm -r -f libloader.zip > /dev/null
	rm -r -f Tweak > /dev/null
	rm -r -f CydiaSubstrateFramework > /dev/null
	rm -r -f libloader > /dev/null
	echo "Packaging IPA"
	zip -r -X ../"AccuWeather++.ipa" * > /dev/null
	cd ../; rm -r -f AccuWeather > /dev/null
	echo "Done Building AccuWeather++"
}

function audiomackpp {
	echo "Building Audiomack++"
	cd ~/Desktop/Ipas
	mkdir -p Build
	cd Build
	rm -r -f Audiomack > /dev/null
	echo "Extracting IPA"
	unzip ../Audiomack.ipa -d Audiomack > /dev/null
	cd "Audiomack";
	echo "Downloading Tweak"
	curl -O "https://raw.githubusercontent.com/SarahH12099/SarahH12099.github.io/master/repo/debs/Audiomack.deb"
	echo "Downloading Tweak Dependencies"
	curl -O "https://raw.githubusercontent.com/SarahH12099/Auto-IPA-Builder/master/Files/CydiaSubstrateFramework.zip"
	curl -O "https://raw.githubusercontent.com/SarahH12099/Auto-IPA-Builder/master/Files/libloader.zip"
	echo "Extracting Tweak And Tweak Dependencies"
	dpkg-deb -R "Audiomack.deb" Tweak > /dev/null
	unzip CydiaSubstrateFramework.zip -d CydiaSubstrateFramework > /dev/null
	unzip libloader.zip -d libloader > /dev/null
	echo "Converting Tweak To Non-Jailbreak"
	cd Tweak/Library/MobileSubstrate/DynamicLibraries
	install_name_tool -change /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate @rpath/CydiaSubstrate.framework/CydiaSubstrate "AudiomackCrack.dylib" > /dev/null
	echo "Moving Tweak And Tweak Dependencies"
	cd ../../../../
	mkdir -p Payload/audiomack-iphone.app/libloader > /dev/null
	cp Tweak/Library/MobileSubstrate/DynamicLibraries/AudiomackCrack.dylib Payload/audiomack-iphone.app/libloader > /dev/null
	cp libloader/Sys.dylib Payload/audiomack-iphone.app > /dev/null
	cp -R CydiaSubstrateFramework/Frameworks Payload/audiomack-iphone.app > /dev/null
	echo "Injecting Tweak"
	cd Payload/audiomack-iphone.app
	install_name_tool -change /usr/lib/libSystem.B.dylib @executable_path/Sys.dylib "audiomack-iphone" > /dev/null
	cd ../../
	echo "Cleaning Left Over Files"
	rm -r -f Audiomack.deb > /dev/null
	rm -r -f CydiaSubstrateFramework.zip > /dev/null
	rm -r -f libloader.zip > /dev/null
	rm -r -f Tweak > /dev/null
	rm -r -f CydiaSubstrateFramework > /dev/null
	rm -r -f libloader > /dev/null
	echo "Packaging IPA"
	zip -r -X ../"Audiomack++.ipa" * > /dev/null
	cd ../; rm -r -f Audiomack > /dev/null
	echo "Done Building Audiomack++"
}

function cercube {
	echo "Building Cercube for YouTube"
	cd ~/Desktop/Ipas
	mkdir -p Build
	cd Build
	rm -r -f YouTube > /dev/null
	echo "Extracting IPA"
	unzip ../YouTube.ipa -d YouTube > /dev/null
	cd "YouTube";
	echo "Downloading Tweak"
	curl -O "https://raw.githubusercontent.com/SarahH12099/Auto-IPA-Builder/master/Tweaks/Cercube.zip"
	echo "Downloading Tweak Dependencies"
	curl -O "https://raw.githubusercontent.com/SarahH12099/Auto-IPA-Builder/master/Files/libloader.zip"
	echo "Extracting Tweak And Tweak Dependencies"
	unzip Cercube.zip -d Tweak > /dev/null
	unzip libloader.zip -d libloader > /dev/null
	echo "Moving Tweak And Tweak Dependencies"
	mkdir -p Payload/YouTube.app/libloader > /dev/null
	cp Tweak/Cercube.dylib Payload/YouTube.app/libloader > /dev/null
	cp libloader/Sys.dylib Payload/YouTube.app > /dev/null
	cp -R Tweak/Carida.bundle Payload/YouTube.app > /dev/null
	echo "Injecting Tweak"
	cd Payload/YouTube.app
	install_name_tool -change /usr/lib/libSystem.B.dylib @executable_path/Sys.dylib "YouTube" > /dev/null
	cd ../../
	echo "Cleaning Left Over Files"
	rm -r -f Cercube.zip > /dev/null
	rm -r -f libloader.zip > /dev/null
	rm -r -f Tweak > /dev/null
	rm -r -f libloader > /dev/null
	echo "Packaging IPA"
	zip -r -X ../"Cercube for YouTube.ipa" * > /dev/null
	cd ../; rm -r -f YouTube > /dev/null
	echo "Building Cercube for YouTube"
}

function cercubepp {
	echo "Building Cercube for YouTube++"
	cd ~/Desktop/Ipas
	mkdir -p Build
	cd Build
	rm -r -f YouTube > /dev/null
	echo "Extracting IPA"
	unzip ../YouTube.ipa -d YouTube > /dev/null
	cd "YouTube";
	echo "Downloading Tweak"
	curl -O "https://raw.githubusercontent.com/SarahH12099/Auto-IPA-Builder/master/Tweaks/CercubePP.zip"
	echo "Downloading Tweak Dependencies"
	curl -O "https://raw.githubusercontent.com/SarahH12099/Auto-IPA-Builder/master/Tweaks/Cercube.zip"
	curl -O "https://raw.githubusercontent.com/SarahH12099/Auto-IPA-Builder/master/Files/libloader.zip"
	echo "Extracting Tweak And Tweak Dependencies"
	unzip Cercube.zip -d Tweak > /dev/null
	unzip CercubePP.zip -d Pass > /dev/null
	unzip libloader.zip -d libloader > /dev/null
	echo "Moving Tweak And Tweak Dependencies"
	mkdir -p Payload/YouTube.app/libloader > /dev/null
	cp Tweak/Cercube.dylib Payload/YouTube.app/libloader > /dev/null
	cp Pass/CercubePass.dylib Payload/YouTube.app/libloader > /dev/null
	cp libloader/Sys.dylib Payload/YouTube.app > /dev/null
	cp -R Tweak/Carida.bundle Payload/YouTube.app > /dev/null
	echo "Injecting Tweak"
	cd Payload/YouTube.app
	install_name_tool -change /usr/lib/libSystem.B.dylib @executable_path/Sys.dylib "YouTube" > /dev/null
	cd ../../
	echo "Cleaning Left Over Files"
	rm -r -f Cercube.zip > /dev/null
	rm -r -f CercubePP.zip > /dev/null
	rm -r -f libloader.zip > /dev/null
	rm -r -f Tweak > /dev/null
	rm -r -f Pass > /dev/null
	rm -r -f libloader > /dev/null
	echo "Packaging IPA"
	zip -r -X ../"Cercube for YouTube++.ipa" * > /dev/null
	cd ../; rm -r -f YouTube > /dev/null
	echo "Building Cercube for YouTube++"
}

function twitchpp {
	echo "Building Twitch++"
	cd ~/Desktop/Ipas
	mkdir -p Build
	cd Build
	rm -r -f Twitch > /dev/null
	echo "Extracting IPA"
	unzip ../Twitch.ipa -d Twitch > /dev/null
	cd "Twitch";
	echo "Downloading Tweak"
	curl -O "https://raw.githubusercontent.com/SarahH12099/SarahH12099.github.io/master/repo/debs/Twitch.deb"
	echo "Downloading Tweak Dependencies"
	curl -O "https://raw.githubusercontent.com/SarahH12099/Auto-IPA-Builder/master/Files/CydiaSubstrateFramework.zip"
	curl -O "https://raw.githubusercontent.com/SarahH12099/Auto-IPA-Builder/master/Files/libloader.zip"
	echo "Extracting Tweak And Tweak Dependencies"
	dpkg-deb -R "Twitch.deb" Tweak > /dev/null
	unzip CydiaSubstrateFramework.zip -d CydiaSubstrateFramework > /dev/null
	unzip libloader.zip -d libloader > /dev/null
	echo "Converting Tweak To Non-Jailbreak"
	cd Tweak/Library/MobileSubstrate/DynamicLibraries
	install_name_tool -change /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate @rpath/CydiaSubstrate.framework/CydiaSubstrate "TwitchCrack.dylib" > /dev/null
	echo "Moving Tweak And Tweak Dependencies"
	cd ../../../../
	mkdir -p Payload/Twitch.app/libloader > /dev/null
	cp Tweak/Library/MobileSubstrate/DynamicLibraries/TwitchCrack.dylib Payload/Twitch.app/libloader > /dev/null
	cp libloader/Sys.dylib Payload/Twitch.app > /dev/null
	cp -R CydiaSubstrateFramework/Frameworks Payload/Twitch.app > /dev/null
	echo "Injecting Tweak"
	cd Payload/Twitch.app
	install_name_tool -change /usr/lib/libSystem.B.dylib @executable_path/Sys.dylib "Twitch" > /dev/null
	cd ../../
	echo "Cleaning Left Over Files"
	rm -r -f Twitch.deb > /dev/null
	rm -r -f CydiaSubstrateFramework.zip > /dev/null
	rm -r -f libloader.zip > /dev/null
	rm -r -f Tweak > /dev/null
	rm -r -f CydiaSubstrateFramework > /dev/null
	rm -r -f libloader > /dev/null
	echo "Packaging IPA"
	zip -r -X ../"Twitch++.ipa" * > /dev/null
	cd ../; rm -r -f Twitch > /dev/null
	echo "Done Building Twitch++"
}

function zinitevipp {
	echo "Building ZiniTevi++"
	cd ~/Desktop/Ipas
	mkdir -p Build
	cd Build
	rm -r -f ZiniTevi > /dev/null
	echo "Extracting IPA"
	unzip ../ZiniTevi.ipa -d ZiniTevi > /dev/null
	cd "ZiniTevi";
	echo "Downloading Tweak"
	curl -O "https://raw.githubusercontent.com/SarahH12099/SarahH12099.github.io/master/repo/debs/ZiniTevi.deb"
	echo "Downloading Tweak Dependencies"
	curl -O "https://raw.githubusercontent.com/SarahH12099/Auto-IPA-Builder/master/Files/CydiaSubstrateFramework.zip"
	curl -O "https://raw.githubusercontent.com/SarahH12099/Auto-IPA-Builder/master/Files/libloader.zip"
	echo "Extracting Tweak And Tweak Dependencies"
	dpkg-deb -R "ZiniTevi.deb" Tweak > /dev/null
	unzip CydiaSubstrateFramework.zip -d CydiaSubstrateFramework > /dev/null
	unzip libloader.zip -d libloader > /dev/null
	echo "Converting Tweak To Non-Jailbreak"
	cd Tweak/Library/MobileSubstrate/DynamicLibraries
	install_name_tool -change /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate @rpath/CydiaSubstrate.framework/CydiaSubstrate "ZiniTeviCrack.dylib" > /dev/null
	echo "Moving Tweak And Tweak Dependencies"
	cd ../../../../
	mkdir -p Payload/ZiniTevi.app/libloader > /dev/null
	cp Tweak/Library/MobileSubstrate/DynamicLibraries/ZiniTeviCrack.dylib Payload/ZiniTevi.app/libloader > /dev/null
	cp libloader/Sys.dylib Payload/ZiniTevi.app > /dev/null
	cp -R CydiaSubstrateFramework/Frameworks Payload/ZiniTevi.app > /dev/null
	echo "Injecting Tweak"
	cd Payload/ZiniTevi.app
	install_name_tool -change /usr/lib/libSystem.B.dylib @executable_path/Sys.dylib "ZiniTevi" > /dev/null
	cd ../../
	echo "Cleaning Left Over Files"
	rm -r -f ZiniTevi.deb > /dev/null
	rm -r -f CydiaSubstrateFramework.zip > /dev/null
	rm -r -f libloader.zip > /dev/null
	rm -r -f Tweak > /dev/null
	rm -r -f CydiaSubstrateFramework > /dev/null
	rm -r -f libloader > /dev/null
	echo "Packaging IPA"
	zip -r -X ../"ZiniTevi++.ipa" * > /dev/null
	cd ../; rm -r -f ZiniTevi > /dev/null
	echo "Done Building ZiniTevi++"
}

"$1" "${@:2}"